### ISSUE TITLE
Support for request/response as in MQTT v5?

### ISSUE THREAD

**Issue by IvanBelyakoff** [emqx/qmqtt#206] opened 2020-09-01 08:20 UTC
Hi guys, is there any support for it, maybe undocumented?

I don't see currently from the code how I can do that, only implement publishing/subscription to particular topics by hand.

**Comment by mwallnoefer** [comment] 2020-09-02 11:49
_eqmqtt_ is in maintenance phase only and will not be extended with new features. This is a duplicate of issue #188, so please have a look there.

**Closed by mwallnoefer** 2020-09-02 11:49 UTC
